### ISSUE TITLE
RTMP Source does not work with AWS MediaLive

### ISSUE THREAD

**Issue by philipgiuliani** [membraneframework/membrane_rtmp_plugin#45]
When receiving an AWS MediaLive RTMP stream, the library crashes with the following exception:

```
** (ArgumentError) the following keys must also be given when building struct Membrane.RTMP.Messages.SetDataFrame: [:duration, :file_size, :encoder]
--
(membrane_rtmp_plugin 0.11.1) Membrane.RTMP.Messages.SetDataFrame.__struct__/1
(elixir 1.14.2) lib/kernel.ex:2336: Kernel.struct!/2
(membrane_rtmp_plugin 0.11.1) lib/membrane_rtmp_plugin/rtmp/source/message_parser.ex:162: Membrane.RTMP.MessageParser.read_frame/3
(membrane_rtmp_plugin 0.11.1) lib/membrane_rtmp_plugin/rtmp/source/message_parser.ex:70: Membrane.RTMP.MessageParser.handle_packet/2
(membrane_rtmp_plugin 0.11.1) lib/membrane_rtmp_plugin/rtmp/source/message_handler.ex:285: Membrane.RTMP.MessageHandler.parse_packet_messages/3
(pepe 0.1.0) lib/pepe/rtmp/source.ex:69: Pepe.RTMP.Source.handle_info/3
(membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:138: Membrane.Core.CallbackHandler.exec_callback/4
(membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:62: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
Last message: {:tcp, #Port<0.20>, <<4, 0, 0, 0, 0, 0, 184, 18, 0, 0, 0, 0, 2, 0, 13, 64, 115, 101, 116, 68, 97, 116, 97, 70, 114, 97, 109, 101, 2, 0, 10, 111, 110, 77, 101, 116, 97, 68, 97, 116, 97, 3, 0, 12, 97, 117, 100, ...>>}
State: %Membrane.Core.Element.State{module: Pepe.RTMP.Source, type: :source, name: :rtmp_source, internal_state: %{actions: [], epoch: 27861016, header_sent?: false, message_parser: %Membrane.RTMP.MessageParser{state_machine: :connected, buffer: "", chunk_size: 128, handshake: nil, previous_headers: %{3 => %Membrane.RTMP.Header{chunk_stream_id: 3, type_id: 20, body_size: 25, timestamp: 0, timestamp_delta: 0, stream_id: 0}, 4 => %Membrane.RTMP.Header{chunk_stream_id: 4, type_id: 20, body_size: 42, timestamp: 0, timestamp_delta: 0, stream_id: 0}}, current_tx_id: 1}, recv_timer: #Reference<0.945005308.8912897.14298>, socket: #Port<0.20>, socket_module: :gen_tcp, socket_ready?: false, validator: Membrane.RTMP.DefaultMessageValidator}, pads_info: %{output: %{accepted_formats_str: ["Membrane.RemoteStream"], availability: :always, demand_mode: :manual, direction: :output, mode: :push, name: :output, options: nil}}, pads_data: %{output: %Membrane.Element.PadData{availability: :always, stream_format: %Membrane.RemoteStream{content_format: Membrane.FLV, type: :bytestream}, direction: :output, mode: :push, name: :output, ref: :output, options: %{}, pid: #PID<0.2461.0>, other_ref: :input, input_queue: nil, demand: nil, demand_mode: :manual, demand_unit: nil, start_of_stream?: false, end_of_stream?: false, other_demand_unit: :buffers, auto_demand_size: nil, sticky_messages: [], toilet: {Membrane.Core.Element.Toilet, {#PID<0.2472.0>, #Reference<0.945005308.9043969.14253>}, 200, #PID<0.2461.0>, 1, 0}, associated_pads: [], sticky_events: [], stream_format_validation_params: []}}, parent_pid: #PID<0.2093.0>, supplying_demand?: false, delayed_demands: MapSet.new([]), synchronization: %{clock: nil, latency: 0, parent_clock: #PID<0.2095.0>, stream_sync: :membrane_no_sync, timers: %{}}, demand_size: nil, initialized?: true, playback: :playing, playback_queue: [], resource_guard: #PID<0.2459.0>, subprocess_supervisor: #PID<0.2457.0>, terminating?: false}
```

Let us know whether this is known or not for you and if you need any more data for investigating.

**Comment by philipgiuliani** [comment]
We will be working on it tomorrow.

**Comment by dmorn** [comment]
This is the parsed AMF payload:
```
Membrane.RTMP.AMF.Parser.parse(data)
[
  "@setDataFrame",
  "onMetaData",
  %{
    "audiochannels" => 2.0,
    "audiocodecid" => "mp4a",
    "audiodatarate" => 192.0,
    "audiodevice" => "Elemental Technologies Live",
    "audiosamplerate" => 48000.0,
    "language" => ""
  }
]
```
