### ISSUE TITLE
Header.deserialize error in the middle of an RTMP stream

### ISSUE THREAD

**Issue by dmorn** [membraneframework/membrane_rtmp_plugin#48]
We're facing this error that made the whole supervision tree exit:
```
{"time":"2023-05-15T19:50:07.623Z","severity":"error","message":"GenServer #PID<0.1145.3> terminating\n** (KeyError) key :timestamp not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map\n    (membrane_rtmp_plugin 0.11.2) lib/membrane_rtmp_plugin/rtmp/source/header.ex:113: Membrane.RTMP.Header.deserialize/2\n    (membrane_rtmp_plugin 0.11.2) lib/membrane_rtmp_plugin/rtmp/source/message_parser.ex:143: Membrane.RTMP.MessageParser.read_frame/3\n    (membrane_rtmp_plugin 0.11.2) lib/membrane_rtmp_plugin/rtmp/source/message_parser.ex:70: Membrane.RTMP.MessageParser.handle_packet/2\n    (membrane_rtmp_plugin 0.11.2) lib/membrane_rtmp_plugin/rtmp/source/message_handler.ex:288: Membrane.RTMP.MessageHandler.parse_packet_messages/3\n    (pepe 0.1.0) lib/pepe/rtmp/source.ex:74: Pepe.RTMP.Source.handle_info/3\n    (membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:138: Membrane.Core.CallbackHandler.exec_callback/4\n    (membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:62: Membrane.Core.CallbackHandler.exec_and_handle_callback/5\n    (membrane_core 0.11.3) lib/membrane/core/element.ex:228: Membrane.Core.Element.handle_info/2\nLast message: {:tcp, #Port<0.20258>, <<8, 255, 255, 255, 0, 0, 4, 8, 0, 0, 0, 0, 1, 5, 237, 222, 175, 0, 17, 144>>}","metadata":{"domain":["otp"],"erl_level":"error","error":{"initial_call":null,"reason":"** (KeyError) key :timestamp not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map\n    (membrane_rtmp_plugin 0.11.2) lib/membrane_rtmp_plugin/rtmp/source/header.ex:113: Membrane.RTMP.Header.deserialize/2\n    (membrane_rtmp_plugin 0.11.2) lib/membrane_rtmp_plugin/rtmp/source/message_parser.ex:143: Membrane.RTMP.MessageParser.read_frame/3\n    (membrane_rtmp_plugin 0.11.2) lib/membrane_rtmp_plugin/rtmp/source/message_parser.ex:70: Membrane.RTMP.MessageParser.handle_packet/2\n    (membrane_rtmp_plugin 0.11.2) lib/membrane_rtmp_plugin/rtmp/source/message_handler.ex:288: Membrane.RTMP.MessageHandler.parse_packet_messages/3\n    (pepe 0.1.0) lib/pepe/rtmp/source.ex:74: Pepe.RTMP.Source.handle_info/3\n    (membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:138: Membrane.Core.CallbackHandler.exec_callback/4\n    (membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:62: Membrane.Core.CallbackHandler.exec_and_handle_callback/5\n    (membrane_core 0.11.3) lib/membrane/core/element.ex:228: Membrane.Core.Element.handle_info/2\n"},"error_logger":{"report_cb":"&:gen_server.format_log/1","tag":"error"},"mb_prefix":"Pepe.Pipeline/:rtmp_source/"}}
```

The situation is this: in the middle of a stream session another component of the pipeline crashed, restarting it. The RTMP source received a new connection to the producing RTMP server and received this packet, which is a "type2" header which requires previous headers from the same `stream_id` to be processed, which it does not have, and crashed. The problem is that the server kept on sending the same payload (at least, the same type of payload with the same prelude in the header) making it impossible for the pipeline to recover.

Now, what do we want to do in this situation? The RTMP server sending the signal is supposed to be a reliable implementation (Medialive). I did not read the RFC or documentation of RTMP yet so I'm not sure if this is supposed to happen. What if we drop packets until we find a self-contained header? Is it going to happen at some point? I did not experiment with it because it is kind of difficult to reproduce.

**Comment by Janix4000** [comment]
You need to manually close the socket when the pipeline crashes and then attempt to reconnect. The RTMP protocol doesn't have a defined reconnection process during an ongoing stream unless your server has an alternative method. Regardless, it's best to initiate a new connection rather than reuse the old socket for the pipeline.

There is no guarantee to receive another zero-type header in the middle of the stream.

**Comment by dmorn** [comment]
Perfect, thanks!

**Comment by philipgiuliani** [comment]
Hi, we got this issue again after a restart of the pipeline, even after rewriting our socket handling implementation. The interesting thing that we noticed this time is that even if we restart our app, the RTMP is crashing with this error. This happened event after trying to restart it one hour later.

**Comment by philipgiuliani** [comment]
Some more data:
```
Last message: {:tcp, #Port<0.11>, <<8, 255, 255, 255, 0, 0, 4, 8, 0, 0, 0, 0, 1, 78, 211, 136, 175, 0, 17, 144, 72, 0, 0, 1, 0, 1, 196, 8, 175, 1, 33, 27, 20, 85, 252, 224, 96, 4, 25, 154, 144, 93, 223, 46, 152, 85, 212, ...>>}
```

```
State: %Membrane.Core.Element.State{module: Pepe.RTMP.Source, type: :source, name: :rtmp_source, internal_state: %{actions: [], epoch: 24882536, header_sent?: false, message_parser: %Membrane.RTMP.MessageParser{state_machine: :connecting, buffer: \"\", chunk_size: 15000, handshake: nil, previous_headers: %{2 => %Membrane.RTMP.Header{chunk_stream_id: 2, type_id: 1, body_size: 4, timestamp: 0, timestamp_delta: 0, extended_timestamp?: false, stream_id: 0}, 3 => %Membrane.RTMP.Header{chunk_stream_id: 3, type_id: 20, body_size: 25, timestamp: 0, timestamp_delta: 0, extended_timestamp?: false, stream_id: 0}, 4 => %Membrane.RTMP.Header{chunk_stream_id: 4, type_id: 18, body_size: 184, timestamp: 0, timestamp_delta: 0, extended_timestamp?: false, stream_id: 0}}, current_tx_id: 1}, recv_timer: #Reference<0.1082275829.3332898817.155508>, socket: #Port<0.11>, socket_module: :gen_tcp, socket_ready?: false, validator: %Pepe.RTMP.StreamKeyValidator{allowed_key: \"YqceH9wqOi1j\"}}
```

**Comment by philipgiuliani** [comment]
We found out, that the crash happens when the rtmp starts after the extended timestamp threshold (> 4 hours 40 minutes).
